### ISSUE TITLE
 运行nim c -r build.nim遇到错误，怎么修复？

### ISSUE THREAD

**Issue by brightmann** [muxueqz/kun#2]
hi。

$ nim c -r build.nim
Hint: used config file 'C:\Users\12799\Downloads\Compressed\nim-2.2.0_x64\nim-2.2.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\12799\Downloads\Compressed\nim-2.2.0_x64\nim-2.2.0\config\config.nims' [Conf]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
10257 lines; 0.090s; 10.547MiB peakmem; proj: C:\Users\12799\kun\build.nim; out: C:\Users\12799\kun\build.exe [SuccessX]
Hint: C:\Users\12799\kun\build.exe [Exec]
srcs\example.md
WARNING THIS IS AN DEBUG BUILD. NWT PARSES THE HTML ON EVERY GET; THIS IS SLOW
srcs\hf.md
WARNING THIS IS AN DEBUG BUILD. NWT PARSES THE HTML ON EVERY GET; THIS IS SLOW
WARNING THIS IS AN DEBUG BUILD. NWT PARSES THE HTML ON EVERY GET; THIS IS SLOW
WARNING THIS IS AN DEBUG BUILD. NWT PARSES THE HTML ON EVERY GET; THIS IS SLOW
C:\Users\12799\kun\build.nim(304) build
C:\Users\12799\kun\build.nim(298) main
C:\Users\12799\kun\build.nim(287) write_tags
C:\Users\12799\Downloads\Compressed\nim-2.2.0_x64\nim-2.2.0\lib\std\syncio.nim(868) writeFile
Error: unhandled exception: **cannot open: public/tags/nim.html** [IOError]
Error: execution of an external program failed: 'C:\Users\12799\kun\build.exe'

12799@DESKTOP-B6LK9IO MINGW64 ~/kun (master)
$ ls public
example.html  happy-festival.html  index.html  static/

 public目录里，根本没有tags目录，怎么修复？
谢谢你！

**Comment by muxueqz** [comment]
@brightmann 请再git pull一下试试

**Comment by brightmann** [comment]
hi.
这次运行命令nim c -r build.nim成功。我搭建的博客的网址：
https://tangerine-bienenstitch-f479e0.netlify.app/ ，不过访问访问里面的链接都不显示内容，比如：
https://tangerine-bienenstitch-f479e0.netlify.app/happy-festival，网址后面加上 .html 还是打不开链接: https://tangerine-bienenstitch-f479e0.netlify.app/happy-festival.html
我看了一下happy-festival.html的html codes,里面显示：
....
<title>快乐的节日
<article>
  <h1>快乐的节日</h1>
  <aside>
    <div id="sub-header">
      2024-11-03 01:25
            <a class="label" href="/tags/nim.html">
        nim
        </a>

    · <a href="/">view all posts</a>
    </div>
  </aside>
  <content>
    <iframe width="350" height="200" src="http://videa.hu/player?a=dPKRSOb6TAMq1oCW"></iframe>

  </content>
</article>
....

难道是生成的html文件不正常？
谢谢回复！

**Comment by muxueqz** [comment]
@brightmann 看起来确实是html内容不正常，我重新build也是正常的，你可以把你的 srcs push到github看看吗？

**Comment by brightmann** [comment]
hi

已把md files发到你邮箱。

**Comment by muxueqz** [comment]
@brightmann 看起来没问题，我在我的环境测试，输出的html也是正确的，不过我没有在Windows中测试过，不清楚会不会与此有关

**Comment by brightmann** [comment]
hi.

可能真的是跟windows有关。我在linux vps上，搭建了nim环境，然后用你这个程序生成了静态网站的根目录，并把根目录的内容上传到了netlify.com, 网站地址: https://effervescent-narwhal-271ea8.netlify.app/, 不过我好奇到底是什么原因导致 windows上不成功的？我等下把windows上生成的html文件发到你邮箱，你看看windows上生成的html文件到底哪里有问题，谢谢你的回复

**Comment by muxueqz** [comment]
@brightmann 可能是html template engine的原因，我更新了一下，你再试试？

**Comment by luckypoemster** [comment]
hi.

遇到很多错误。算了，你还是roll back之前的状态，我就在linux上，安装即可。

**Comment by muxueqz** [comment]
@luckypoemster ok, 换了html template engine之后需要运行nimble install nimja，我在github actions里的Windows是可以build的

**Comment by luckypoemster** [comment]
现在在windows上，也正常了。谢谢你！
